dist: trusty
sudo: false
language: elixir
elixir: '1.7.3'
otp_release: '21.1.1'
matrix:
  include:
    - elixir: '1.7.3'
      otp_release: '21.1.1'
    - elixir: '1.5'
      otp_release: '20.3'
    - elixir: '1.4'
      otp_release: '20.3'

addons:
  postgresql: "9.4"
services:
  - postgresql
